apiVersion: apps/v1
kind: Deployment
metadata:
  name: digicache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digicache
  template:
    metadata:
      labels:
        app: digicache
    spec:
      containers:
        - name: digicache-container
          image: aprilschen/digicache:latest
          ports:
            - containerPort: 3000
