# Generated by Django 4.1.6 on 2023-02-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('description', models.TextField(max_length=2000)),
                ('tags', models.CharField(max_length=2000)),
            ],
        ),
    ]
