# Generated by Django 4.1.6 on 2023-02-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digicacheAPI', '0003_alter_cache_latitude_alter_cache_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
