# Generated by Django 4.1.6 on 2023-02-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digicacheAPI', '0004_cache_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='cache',
            name='tags',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
