# Generated by Django 4.1.6 on 2023-02-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digicacheAPI', '0005_alter_cache_description_alter_cache_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='cache',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
