# Generated by Django 4.1.6 on 2023-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digicacheAPI', '0006_alter_cache_date_alter_cache_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
